require_relative '../spec_helper.rb'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GoalUpdatesController do

  # This should return the minimal set of attributes required to create a valid
  # GoalUpdate. As you add validations to GoalUpdate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "goal_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoalUpdatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all goal_updates as @goal_updates" do
      goal_update = GoalUpdate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:goal_updates).should eq([goal_update])
    end
  end

  describe "GET show" do
    it "assigns the requested goal_update as @goal_update" do
      goal_update = GoalUpdate.create! valid_attributes
      get :show, {:id => goal_update.to_param}, valid_session
      assigns(:goal_update).should eq(goal_update)
    end
  end

  describe "GET new" do
    it "assigns a new goal_update as @goal_update" do
      get :new, {}, valid_session
      assigns(:goal_update).should be_a_new(GoalUpdate)
    end
  end

  describe "GET edit" do
    it "assigns the requested goal_update as @goal_update" do
      goal_update = GoalUpdate.create! valid_attributes
      get :edit, {:id => goal_update.to_param}, valid_session
      assigns(:goal_update).should eq(goal_update)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GoalUpdate" do
        expect {
          post :create, {:goal_update => valid_attributes}, valid_session
        }.to change(GoalUpdate, :count).by(1)
      end

      it "assigns a newly created goal_update as @goal_update" do
        post :create, {:goal_update => valid_attributes}, valid_session
        assigns(:goal_update).should be_a(GoalUpdate)
        assigns(:goal_update).should be_persisted
      end

      it "redirects to the created goal_update" do
        post :create, {:goal_update => valid_attributes}, valid_session
        response.should redirect_to(GoalUpdate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved goal_update as @goal_update" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoalUpdate.any_instance.stub(:save).and_return(false)
        post :create, {:goal_update => { "goal_id" => "invalid value" }}, valid_session
        assigns(:goal_update).should be_a_new(GoalUpdate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoalUpdate.any_instance.stub(:save).and_return(false)
        post :create, {:goal_update => { "goal_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested goal_update" do
        goal_update = GoalUpdate.create! valid_attributes
        # Assuming there are no other goal_updates in the database, this
        # specifies that the GoalUpdate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GoalUpdate.any_instance.should_receive(:update).with({ "goal_id" => "1" })
        put :update, {:id => goal_update.to_param, :goal_update => { "goal_id" => "1" }}, valid_session
      end

      it "assigns the requested goal_update as @goal_update" do
        goal_update = GoalUpdate.create! valid_attributes
        put :update, {:id => goal_update.to_param, :goal_update => valid_attributes}, valid_session
        assigns(:goal_update).should eq(goal_update)
      end

      it "redirects to the goal_update" do
        goal_update = GoalUpdate.create! valid_attributes
        put :update, {:id => goal_update.to_param, :goal_update => valid_attributes}, valid_session
        response.should redirect_to(goal_update)
      end
    end

    describe "with invalid params" do
      it "assigns the goal_update as @goal_update" do
        goal_update = GoalUpdate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoalUpdate.any_instance.stub(:save).and_return(false)
        put :update, {:id => goal_update.to_param, :goal_update => { "goal_id" => "invalid value" }}, valid_session
        assigns(:goal_update).should eq(goal_update)
      end

      it "re-renders the 'edit' template" do
        goal_update = GoalUpdate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoalUpdate.any_instance.stub(:save).and_return(false)
        put :update, {:id => goal_update.to_param, :goal_update => { "goal_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested goal_update" do
      goal_update = GoalUpdate.create! valid_attributes
      expect {
        delete :destroy, {:id => goal_update.to_param}, valid_session
      }.to change(GoalUpdate, :count).by(-1)
    end

    it "redirects to the goal_updates list" do
      goal_update = GoalUpdate.create! valid_attributes
      delete :destroy, {:id => goal_update.to_param}, valid_session
      response.should redirect_to(goal_updates_url)
    end
  end

end
